/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#6e9fff",
        "secondary-container": "#3c475a",
        "surface-container-low": "#131315",
        "on-surface-variant": "#adaaad",
        "on-tertiary-fixed-variant": "#003d5a",
        "outline": "#767577",
        "on-primary-container": "#002150",
        "inverse-primary": "#005bc4",
        "primary-dim": "#699cff",
        "tertiary-container": "#34b5fa",
        "on-tertiary-container": "#003047",
        "error": "#ff716c",
        "tertiary-dim": "#17a8ec",
        "on-background": "#f9f5f8",
        "on-primary": "#002c66",
        "on-primary-fixed": "#000000",
        "on-tertiary": "#003b56",
        "primary": "#85adff",
        "inverse-surface": "#fcf8fb",
        "on-secondary-fixed-variant": "#515c70",
        "surface-container-lowest": "#000000",
        "primary-fixed": "#6e9fff",
        "inverse-on-surface": "#565457",
        "surface-variant": "#262528",
        "surface-dim": "#0e0e10",
        "tertiary": "#61c2ff",
        "tertiary-fixed-dim": "#25adf1",
        "surface": "#0e0e10",
        "primary-fixed-dim": "#5391ff",
        "surface-bright": "#2c2c2f",
        "on-secondary-container": "#c5d1e8",
        "on-secondary": "#475266",
        "secondary-fixed": "#d8e3fb",
        "outline-variant": "#48474a",
        "surface-container-high": "#1f1f22",
        "surface-container-highest": "#262528",
        "secondary-fixed-dim": "#cad5ed",
        "on-primary-fixed-variant": "#002a62",
        "on-error-container": "#ffa8a3",
        "error-container": "#9f0519",
        "on-surface": "#f9f5f8",
        "secondary-dim": "#cad5ed",
        "background": "#0e0e10",
        "on-error": "#490006",
        "error-dim": "#d7383b",
        "surface-container": "#19191c",
        "secondary": "#d8e3fb",
        "on-tertiary-fixed": "#001a29",
        "tertiary-fixed": "#40bbff",
        "surface-tint": "#85adff",
        "on-secondary-fixed": "#354053"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
